# Site settings
title: Sophia Diggs-Galligan
email: hi@sophiadg.com
description: Artist and researcher living in San Francisco, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sophiadg.com"

# Build settings — no theme; fully custom layout
# theme: minima

collections:
  projects:
    output: true 
    permalink: /projects/:slug/
    sort_by: priority
    sitemap: true
  publications:
    sort_by: date
    sitemap: true

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  mathjax: false
future: true
jailed: false
gfm_quirks: paragraph_end

markdown: kramdown

defaults:
  - scope:
      path: ""          # An empty string here means "all files"
      type: "projects"  # This matches your collection name
    values:
      layout: "project" # The name of your new layout file (project.html)

