# Site settings
title: Sophia Diggs-Galligan
email: hi@sophiadg.com
description: Artist and researcher living in San Francisco, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sophiadg.com"

# Build settings — no theme; fully custom layout
# theme: minima

collections:
  projects:
    sort_by: priority
    sitemap: true

github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
 mathjax: false
future: true
jailed: false
gfm_quirks: paragraph_end

markdown: kramdown
