# Site settings
title: Sophia Diggs-Galligan
email: hi@sophiadg.com
description: Artist and researcher living in San Francisco, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sophiadg.com"
og_image: "https://sophiadg.com/assets/images/sophia_pic.webp"
github_username: sediggsgalligan

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true 
    permalink: /projects/:slug/
    sort_by: priority
    sitemap: true
  publications:
    sort_by: date
    sitemap: true

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  mathjax: false
future: true
jailed: false
gfm_quirks: paragraph_end

markdown: kramdown

defaults:
  - scope:
      path: ""          # An empty string here means "all files"
      type: "projects"  # This matches your collection name
    values:
      layout: "project" # The name of your new layout file (project.html)

env:
  EMAILJS_PUBLIC_KEY: 4672O2UmK4kpMYRKd
  EMAILJS_SERVICE_ID: service_15fk9jf
  EMAILJS_TEMPLATE_ID: template_b2nibgk
